from pyrogram import Client, filters
from pyrogram.types import Message
from config import SUDO_USERS

@Client.on_message(
    filters.command(["dinosaur"], ".") & (filters.me | filters.user(SUDO_USERS))
)
async def dinosaur(client: Client, message: Message):
    e = await message.edit("`ᴅɪɴ ᴅɪɴɴɴ.......`")
    await e.edit("`ᴅɪɴᴏᴏᴏᴏsᴀᴜʀᴜsssss....!!`")
    await e.edit("`🏃                        🦖`")
    await e.edit("`🏃                       🦖`")
    await e.edit("`🏃                      🦖`")
    await e.edit("`🏃                     🦖`")
    await e.edit("`🏃   `ʟᴀʀɪᴜs`          🦖`")
    await e.edit("`🏃                   🦖`")
    await e.edit("`🏃                  🦖`")
    await e.edit("`🏃                 🦖`")
    await e.edit("`🏃                🦖`")
    await e.edit("`🏃               🦖`")
    await e.edit("`🏃              🦖`")
    await e.edit("`🏃             🦖`")
    await e.edit("`🏃            🦖`")
    await e.edit("`🏃           🦖`")
    await e.edit("`🏃ᴡᴏᴀʀɢʜ..!   🦖`")
    await e.edit("`🏃           🦖`")
    await e.edit("`🏃            🦖`")
    await e.edit("`🏃             🦖`")
    await e.edit("`🏃              🦖`")
    await e.edit("`🏃               🦖`")
    await e.edit("`🏃                🦖`")
    await e.edit("`🏃                 🦖`")
    await e.edit("`🏃                  🦖`")
    await e.edit("`🏃                   🦖`")
    await e.edit("`🏃                    🦖`")
    await e.edit("`🏃                     🦖`")
    await e.edit("`🏃  ʜᴜʜ-ʜᴜʜ           🦖`")
    await e.edit("`🏃                   🦖`")
    await e.edit("`🏃                  🦖`")
    await e.edit("`🏃                 🦖`")
    await e.edit("`🏃                🦖`")
    await e.edit("`🏃               🦖`")
    await e.edit("`🏃              🦖`")
    await e.edit("`🏃             🦖`")
    await e.edit("`🏃            🦖`")
    await e.edit("`🏃           🦖`")
    await e.edit("`🏃          🦖`")
    await e.edit("`🏃         🦖`")
    await e.edit("`ʜᴇ ᴡᴀs ɢᴇᴛᴛɪɴɢ ᴄʟᴏsᴇʀ.....!!!`")
    await e.edit("`🏃       🦖`")
    await e.edit("`🏃      🦖`")
    await e.edit("`🏃     🦖`")
    await e.edit("`🏃    🦖`")
    await e.edit("`ᴊᴜsᴛ ɢɪᴠᴇ ᴜᴘ`")
    await asyncio.sleep(1)
    await e.edit("`🧎🦖`")
    await e.edit("`-ᴅɪᴇᴅ`")
